urls.py
from django.conf.urls.defaults import *
from rangedogs.rangereport.models import *
import random
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', 'django.views.generic.simple.direct_to_template', {'template': 'index.html'}),

    (r'^reports/$', 'django.views.generic.list_detail.object_list', {'queryset': Report.objects.all(), 'paginate_by': 25, 'template_object_name': 'reports'}),
    (r'^report/add/$', 'rangedogs.rangereport.views.smart_create', {'model': Report, 'login_required': True}),
    (r'^report/edit/(?P<object_id>\d+)/$', 'rangedogs.rangereport.views.limited_update', {'model': Report, 'login_required': True}),
    (r'^report/delete/(?P<object_id>\d+)/$', 'rangedogs.rangereport.views.limited_delete', {'model': Report, 'login_required': True}),
    (r'^report/(?P<object_id>\d+)/$', 'django.views.generic.list_detail.object_detail', {'queryset': Report.objects.all(), 'template_object_name': 'report'}),
    (r'^report/random/$', 'django.views.generic.list_detail.object_detail', {'queryset': Report.objects.all(), 'object_id': random.randint(0, Report.objects.count()), 'template_object_name': 'report'}),

    (r'^calibers/$', 'django.views.generic.list_detail.object_list', {'queryset': Caliber.objects.all(), 'template_object_name': 'calibers'}),
    (r'^caliber/(?P<slug>[a-z0-9_-]+)/handloads/$', 'rangedogs.rangereport.views.limited_list', {'model': Handload, 'restrict_field': 'caliber__slug', 'template_object_name': 'caliber', 'extra_context': {'add_title': 'caliber'}}),
    (r'^caliber/(?P<slug>[a-z0-9_-]+)/guns/$', 'rangedogs.rangereport.views.limited_list', {'model': Gun, 'restrict_field': 'caliber__slug', 'template_object_name': 'caliber', 'extra_context': {'add_title': 'caliber'}}),
    (r'^caliber/(?P<slug>[a-z0-9_-]+)/$', 'django.views.generic.list_detail.object_detail', {'queryset': Caliber.objects.all(), 'template_object_name': 'caliber'}),

    (r'^handload/add/$', 'rangedogs.rangereport.views.smart_create', {'model': Handload, 'login_required': True}),
    (r'^handload/edit/(?P<object_id>\d+)/$', 'rangedogs.rangereport.views.limited_update', {'model': Handload, 'login_required': True}),
    (r'^handload/delete/(?P<object_id>\d+)/$', 'rangedogs.rangereport.views.limited_delete', {'model': Handload, 'login_required': True}),
    (r'^handload/(?P<object_id>\d+)/$', 'django.views.generic.list_detail.object_detail', {'queryset': Handload.objects.all(), 'template_object_name': 'handload'}),

    (r'^gun/add/$', 'rangedogs.rangereport.views.smart_create', {'model': Gun, 'login_required': True}),
    (r'^gun/edit/(?P<object_id>\d+)/$', 'rangedogs.rangereport.views.limited_update', {'model': Gun, 'login_required': True}),
    (r'^gun/delete/(?P<object_id>\d+)/$' 'rangedogs.rangereport.views.limited_delete', {'model': Gun, 'login_required': True}),
    (r'^gun/(?P<object_id>\d+)/', 'django.views.generic.list_detail.object_detail', {'queryset': Gun.objects.all(), 'template_object_name': 'gun'}),

    (r'^comment/$', 'rangedogs.rangereport.views.post_comment'),
    (r'^comment/edit/(?P<object_id>\d+)/$', 'rangedogs.rangereport.views.limited_update', {'model': Comment, 'login_required': True}),
    (r'^comment/delete/(?P<object_id>\d+)/$', 'rangedogs.rangereport.views.limited_delete', {'model': Comment, 'login_required': True}),

    (r'^user/(?P<slug>[a-zA-Z0-9_]+)/$', 'django.views.generic.list_detail.object_detail', {'queryset': User.objects.all(), 'slug_field': 'username', 'template_object_name': 'user_obj', 'template_name': 'registration/profile.html'}),
    (r'^user/(?P<slug>[a-zA-Z0-9_]+)/reports/$', 'rangedogs.rangereport.views.limited_list', {'model': Report, 'restrict_field': 'owner__username', 'paginate_by': 25, 'template_object_name': 'reports', 'extra_context': {'add_title': 'user'}}),
    (r'^user/(?P<slug>[a-zA-Z0-9_]+)/guns/$', 'rangedogs.rangereport.views.limited_list', {'model': Gun, 'restrict_field': 'owner__username', 'paginate_by': 100, 'template_object_name': 'guns', 'extra_context': {'add_title': 'user'}}),
    (r'^user/(?P<slug>[a-zA-Z0-9_]+)/handloads/$', 'rangedogs.rangereport.views.limited_list', {'model': Handload, 'restrict_field': 'owner__username', 'paginate_by': 100, 'template_object_name': 'handloads', 'extra_context': {'add_title': 'user'}}),

    #(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    #(r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    #(r'^accounts/create/$', 'rangedogs.rangereport.views.user_create'),
    (r'^accounts/profile/$', 'rangedogs.rangereport.views.user_home'),
    (r'^accounts/profile/edit/$', 'rangedogs.rangereport.views.user_edit'),
    #(r'^accounts/password/change/$', 'django.contrib.auth.views.password_change'),
    #(r'^accounts/password/change/done/$', 'django.contrib.auth.views.password_change_done'),
    #(r'^accounts/password/reset/$', 'django.contrib.auth.views.password_reset'),
    #(r'^accounts/password/reset/done/$', 'django.contrib.auth.views.password_reset_done')
    (r'^accounts/', include('registration.urls')),

    #(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),
)

rangereport/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

class UserProfile(models.Model):
    user = models.ForeignKey(User, unique = True, editable = False)
    location = models.CharField(max_length = 60, blank = True)
    interests = models.TextField(blank = True)
    about = models.TextField(blank = True)

    def get_absolute_url(self):
        return "/user/%s/" % self.user.username

    def __unicode__(self):
        return "<a class=\"userlink\" href=\"/user/%(username)s/\"><img src=\"%(mediaurl)susericon.gif\" alt=\"Rangedogs User\" />%(username)s</a>" % {
                'mediaurl': settings.MEDIA_URL,
                'username': self.user.username }

class Gun(models.Model):
    GUN_TYPES = (
            ('Rifles', (
                ('A', 'Single-shot rifle: falling block'),
                ('B', 'Single-shot rifle: rolling block'),
                ('C', 'Single-shot rifle: break action'),
                ('D', 'Single-shot rifle: bolt action'),
                ('E', 'Single-shot rifle: other'),
                ('F', 'Repeating rifle: bolt action'),
                ('G', 'Repeating rifle: lever action'),
                ('H', 'Autoloading rifle: box magazine/rotating bolt'),
                ('I', 'Autoloading rifle: tubular magazine'),
                ('J', 'Muzzle-loading rifle: matchlock'),
                ('K', 'Muzzle-loading rifle: wheellock'),
                ('L', 'Muzzle-loading rifle: flintlock'),
                ('M', 'Muzzle-loading rifle: percussion cap')
                )
            ),
            ('Handguns', (
                ('N', 'Revolver: single-action'),
                ('O', 'Revolver: double-action'),
                ('P', 'Autoloading pistol: single-action'),
                ('Q', 'autoloading pistol: double-action/single-action'),
                ('R', 'autoloading pistol: double-action only'),
                ('S', 'Single-shot handgun'),
                ('T', 'Muzzle-loading handgun: revolver'),
                ('U', 'Muzzle-loading handgun: single-shot')
                )
            ),
            ('Shotguns', (
                ('V', 'Shotgun: single-shot'),
                ('W', 'Shotgun: double-shot, over/under'),
                ('X', 'Shotgun: double-shot, side-by-side'),
                ('Y', 'Shotgun: pump-action'),
                ('Z', 'Shotgun: autoloading')
                )
            ),
            ('Other', (
                ('1', 'Rifle: other'),
                ('2', 'Handgun: other'),
                ('3', 'Shotgun: other')
                )
            )
    )

    owner = models.ForeignKey(User)
    make = models.CharField(max_length = 120)
    model = models.CharField(max_length = 120)
    type = models.CharField(max_length = 1, choices = GUN_TYPES)
    serial_number = models.CharField(max_length = 120, blank = True)
    caliber = models.ForeignKey('Caliber')
    barrel_length = models.IntegerField(null = True)
    twist_rate = models.CharField(max_length = 40, blank = True)
    source = models.CharField(max_length = 120, blank = True)
    rounds_fired = models.IntegerField(null = True)
    cost = models.DecimalField(max_digits = 8, decimal_places = 2, null = True)
    value = models.DecimalField(max_digits = 8, decimal_places = 2, null = True)
    accessories = models.TextField(blank = True)
    notes = models.TextField(blank = True)
    
    def get_absolute_url(self):
        return "/gun/%s/" % str(self.id)

    def __unicode__(self):
        return "<img src=\"%(mediaurl)sicons/%(type)s.gif\" alt=\"%(typelong)s\" /> %(owner)s's %(make)s %(model)s in %(caliber)s" % {
                'mediaurl': settings.MEDIA_URL,
                'type': self.type,
                'typelong': self.get_type_display(),
                'owner': str(self.owner.get_profile()), 
                'make': self.make, 
                'model': self.model, 
                'caliber': self.caliber.name }

class Caliber(models.Model):
    ROUND_TYPES = (
            ('A', 'Centerfire rifle cartridge'),
            ('B', 'Centerfire handgun cartridge'),
            ('C', 'Rimfire cartridge'),
            ('D', 'Shotgun cartridge'),
            ('E', 'Muzzleloading round')
    )
    slug = models.SlugField(primary_key = True)
    name = models.CharField(max_length = 120)
    type = models.CharField(max_length = 1, choices = ROUND_TYPES)
    notes = models.TextField()
    bullet_dia = models.DecimalField(max_digits = 7, decimal_places = 5, null = True)
    max_oal = models.DecimalField(max_digits = 5, decimal_places = 3, null = True)
    min_oal = models.DecimalField(max_digits = 5, decimal_places = 3, null = True)
    max_case_length = models.DecimalField(max_digits = 5, decimal_places = 3, null = True)
    case_trim_length = models.DecimalField(max_digits = 5, decimal_places = 3, null = True)
    max_pressure = models.IntegerField(null = True)
    pressure_in_CUP = models.BooleanField(null = True)
    reloading_notes = models.TextField()

    def __unicode__(self):
        return self.name

class Handload(models.Model):
    BULLET_TYPES = (
            ('A', 'Spitzer boat-tail'),
            ('B', 'Spitzer'),
            ('C', 'Round-nose'),
            ('D', 'Flat/snub-nose'),
            ('E', 'Wad-cutter'),
            ('F', 'Shotgun shot'),
            ('G', 'Shotgun slug: rifled'),
            ('H', 'Shotgun slug: with sabot')
    )

    BULLET_JACKETS = (
            ('A', 'Full jacket (FMJ)'),
            ('B', 'Partial jacket: soft-point'),
            ('C', 'Partial jacket: plastic/ballistic tip'),
            ('D', 'Partial jacket: hollow-point (JHP)'),
            ('E', 'Gas-checked'),
            ('F', 'No jacket'),
            ('G', 'Hand-made: cast/swaged and jacketed'),
            ('H', 'Hand-made: cast/swaged and gas-checked'),
            ('I', 'Hand-made: cast/swaged and no jacket')
    )

    owner = models.ForeignKey(User, editable = False)
    caliber = models.ForeignKey('Caliber')
    gun = models.ForeignKey('Gun')
    projectile_brand_name = models.CharField(max_length = 120, blank = True)
    projectile_weight = models.IntegerField()
    projectile_type = models.CharField(max_length = 1, choices = BULLET_TYPES)
    projectile_jacket = models.CharField(max_length = 1, choices = BULLET_JACKETS, blank = True)
    projectile_shot_size = models.CharField(max_length = 5, blank = True)
    projectile_shot_material = models.CharField(max_length = 40, blank = True)
    powder_brand = models.CharField(max_length = 60)
    powder_name = models.CharField(max_length = 60)
    powder_weight = models.DecimalField(max_digits = 5, decimal_places = 2)
    pressure = models.IntegerField(null = True)
    pressure_in_CUP = models.BooleanField(null = True)
    velocity = models.DecimalField(max_digits = 5, decimal_places = 1, null = True)
    notes = models.TextField(blank = True)

class Report(models.Model):
    owner = models.ForeignKey(User, editable = False)
    ctime = models.DateTimeField(auto_now_add = True)
    mtime = models.DateTimeField(auto_now = True)
    eventdate = models.DateField()
    participants = models.TextField(blank = True)
    guns = models.ManyToManyField('GunReport')
    title = models.CharField(max_length = 500)
    conditions = models.TextField(blank = True)
    body = models.TextField()

class GunReport(models.Model):
    gun = models.ForeignKey('Gun')
    handloads = models.ManyToManyField('Handload', null = True)
    factory_ammo = models.TextField(blank = True)
    problems = models.TextField(blank = True)
    notes = models.TextField(blank = True)

class Comment(models.Model):
    owner = models.ForeignKey(User, editable = False)
    ctime = models.DateTimeField(auto_now_add = True)
    mtime = models.DateTimeField(auto_now = True)
    User_parent = models.ForeignKey(User, editable = False, related_name = 'private_message')
    Gun_parent = models.ForeignKey('Gun', editable = False)
    Handload_parent = models.ForeignKey('Handload', editable = False)
    Report_parent = models.ForeignKey('Report', editable = False)
    Comment_parent = models.ForeignKey('Comment', editable = False)
    title = models.CharField(max_length = 500)
    body = models.TextField()

rangereport/forms.py
from rangedogs.rangereport.models import *
from django.forms import ModelForm

class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile

class GunForm(ModelForm):
    class Meta:
        model = Gun

templates/rangereport/caliber_detail.html
{% extends "base.html" %}

{% block title %}{{ caliber.name }}{% endblock %}

{% block header %}Caliber Profile: {{ caliber.name }}{% endblock %}

{% block content %}

<p><img src="mediaurl/icons/caliber-{{ caliber.type }}.gif" alt="{{ caliber.get_type_display }}" /> {{ caliber.get_type_display }}</p>

<div class="text">
    {{ caliber.notes }}
</div>

<h2>Reloading data</h2>
<table class="caliber_table">
    <tbody>
        <tr>
            <th>Projectile diameter</th>
            <td>{{ caliber.bullet_dia }}"</td>
        </tr>
        <tr>
            <th>Max case length</th>
            <td>{{ caliber.max_case_length }}"</td>
        </tr>
        <tr>
            <th>Case trim length</th>
            <td>{{ caliber.case_trim_length }}"</td>
        </tr>
        <tr>
            <th>Max overall length</th>
            <td>{{ caliber.max_oal }}"</td>
        </tr>
        <tr>
            <th>Minimum overal length</th>
            <td>{{ caliber.min_oal }}"</td>
        </tr>
        <tr>
            <th>Max pressure {% if caliber.pressure_in_CUP %}(CUP){% else %}(PSI){% endif %}</th>
            <td>{{ caliber.max_pressure }}</td>
        </tr>
    </tbody>
</table>

<div class="text">
    {{ caliber.reloading_notes }}

    <p><a href="/caliber/{{ caliber.slug }}/handloads/">See handloads for this round</a></p>
    <p><a href="/caliber/{{ caliber.slug }}/guns/">See guns chambered in this round</a></p>
</div>

{% endblock %}

templates/rangereport/caliber_list.html
{% extends "base.html" %}

{% block title %}Calibers{% endblock %}

{% block header %}Calibers{% endblock %}

{% block content %}
<ul>
    {% for caliber in calibers_list %}
    <li><a href="/caliber/{{ caliber.slug }}/">{{ caliber }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

templates/rangereport/comment_form.html
{% extends "base.html" %}

{% block content %}
<div class="form">
    <form method="post" action="">
    	{{ form.as_p }}
	<p><input type="submit" value="Submit" /> <input type="reset" value="Reset Form" />
    </form>
</div>
{% endblock %}

templates/rangereport/gun_detail.html
{% extends "base.html" %}
{% load rr_extras %}

{% block title %}Gun Detail{% endblock %}

{% block header %}Gun Detail: {{ gun|safe }}{% endblock %}

{% block content %}
<table>
    <tr>
        <th>Owner</th>
        <td>{{ gun.owner.get_profile|safe }}</td>
    </tr>
    <tr>
        <th>Make</th>
        <td>{{ gun.make }}</td>
    </tr>
    <tr>
        <th>Model</th>
        <td>{{ gun.model }}</td>
    </tr>
    <tr>
        <th>Type</th>
        <td>{{ gun.get_type_display }}</td>
    </tr>
    {% ifequal gun.owner user %}
    {% if gun.serial_number %}
    <tr>
        <th>Serial Number</th>
        <td>{{ gun.serial_number }}</td>
    </tr>
    {% endif %}
    {% endifequal %}
    <tr>
        <th>Caliber</th>
        <td><a href="/caliber/{{ gun.caliber.slug }}/">{{ gun.caliber }}</a></td>
    </tr>
    {% if gun.barrel_length %}
    <tr> 
        <th>Barrel length</th>
        <td>{{ gun.barrel_length }}</td>
    </tr>
    {% endif %}
    {% if gun.twist_rate %}
    <tr>
        <th>Twist rate</th>
        <td>{{ gun.twist_rate }}</td>
    </tr>
    {% endif %}
    {% if gun.source %}
    <tr>
        <th>Source</th>
        <td>{{ gun.source }}</td>
    </tr>
    {% endif %}
    {% if gun.rounds_fired %}
    <tr>
        <th>Rounds fired</th>
        <td>{{ gun.rounds_fired }}</td>
    </tr>
    {% endif %}
    {% if gun.cost %}
    <tr>
        <th>Cost of purchase</th>
        <td>{{ gun.cost }}</td>
    </tr>
    {% endif %}
    {% if gun.value %}
    <tr>
        <th>Estimated value to owner</th>
        <td>{{ gun.value }}</td>
    </tr>
    {% endif %}
    {% if gun.accessories %}
    <tr>
        <th>Accessories</th>
        <td>{{ gun.accessories|removetags:"div span table tr td th thead tbody tfoot style script body head title html embed object param form input textarea marquee meta option"|linebreaks|safe }}</td>
    </tr>
    {% endif %}
    {% if gun.notes %}
    <tr>
        <th>Notes</th>
        <td>{{ gun.notes|removetags:"div span table tr td th thead tbody tfoot style script body head title html embed object param form input textarea marquee meta option"|linebreaks|safe }}</td>
    </tr>
    {% endif %}
</table>

{% ifnotequal gun.handload_set.count 0 %}
<h2>Handloads for this gun:</h2>
<ul>
    {% for handloads in gun.handload_set %}
    <li><a href="/handload/{{ handload.id }}/">Handload ID:{{ handload.id }}</a></li>
    {% endfor %}
</ul>
{% endifnotequal %}

<hr />
{% recurse_comments "Gun" gun.id %}


{% endblock %}

templates/rangereport/gun_form.html
{% extends "base.html" %}

{% block title %}New Gun{% endblock %}

{% block header %}Create a new gun{% endblock %}

{% block content %}
<div class="form">
    <form method="post" action="">
        <p>
            {% if form.make.errors %}
            <span class="error">{{ form.make.errors }}</span>
            {% endif %}
            <label for="id_make"><span class="required">*</span> The maker of the gun:</label><br />
            {{ form.make }}
        </p>
        <p>
            {% if form.model.errors %}
            <span class="error">{{ form.model.errors }}</span>
            {% endif %}
            <label for="id_model"><span class="required">*</span> The model of the gun:</label><br />
            {{ form.model }}
        </p>
        <p>
            {% if form.type.errors %}
            <span class="error">{{ form.type.errors }}</span>
            {% endif %}
            <label for="id_type"><span class="required">*</span> The type of gun:</label><br />
            {{ form.type }}
        </p>
        <p>
            {% if form.caliber.errors %}
            <span class="error">{{ form.caliber.errors }}</span>
            {% endif %}
            <label for="id_caliber"><span class="required">*</span> The caliber of the gun</label><br />
            {{ form.caliber }}
        </p>
        <p>
            {% if form.serial_number.errors %}
            <span class="error">{{ form.serial_number.errors }}</span>
            {% endif %}
            <label for="id_serial_number">The serial number of the gun<br />
            (Note that only you will be able to see this information):</label><br />
            {{ form.serial_number }}
        </p>
        <p>
            {% if form.barrel_length.errors %}
            <span class="error">{{ form.barrel_length.errors }}</span>
            {% endif %}
            <label for="id_barrel_length">The length of the barrel in inches:</label><br />
            {{ form.barrel_length }}
        </p>
        <p>
            {% if form.twist_rate.errors %}
            <span class="error">{{ form.twist_rate.errors }}</span>
            {% endif %}
            <label for="id_twist_rate">The twist-rate of the rifling:</label><br />
            {{ form.twist_rate }}
        </p>
        <p>
            {% if form.source.errors %}
            <span class="error">{{ form.source.errors }}</span>
            {% endif %}
            <label for="id_source">Where you purchased this gun:</label><br />
            {{ form.source }}
        </p>
        <p>
            {% if form.rounds_fired.errors %}
            <span class="error">{{ form.rounds_fired.errors }}</span>
            {% endif %}
            <label for="id_rounds_fired">How many rounds have been fired through this gun<br />
            (Note that, when you submit a range report, this will be automatically updated):</label><br />
            {{ form.rounds_fired }}
        </p>
        <p>
            {% if form.cost.errors %}
            <span class="error">{{ form.cost.errors }}</span>
            {% endif %}
            <label for="id_cost">How much you paid for this gun (in USD):</label><br />
            {{ form.cost }}
        </p>
        <p>
            {% if form.value.errors %}
            <span class="error">{{ form.value.errors }}</span>
            {% endif %}
            <label for="id_value">How much you value this gun to be worth (in USD):</label><br />
            {{ form.value }}
        </p>
        <p>
            {% if form.accessories.errors %}
            <span class="error">{{ form.accessories.errors }}</span>
            {% endif %}
            <label for="id_accessories">Accessories for this gun</label><br />
            {{ form.accessories }}
        </p>
        <p>
            {% if form.notes.errors %}
            <span class="error">{{ form.notes.errors }}</span>
            {% endif %}
            <label for="id_notes">Notes about this gun:</label><br />
            {{ form.notes }}
        </p>
    	<p><input type="submit" value="Submit" /> <input type="reset" value="Reset Form" />
    </form>
</div>
{% endblock %}

templates/rangereport/gun_list.html
{% extends "base.html" %}

{% block title %}Gun List{% endblock %}

{% block header %}<a class="userlink" href="/user/{{ slug }}/"><img src="usericon.gif" alt="Rangedogs User" />{{ slug }}</a>'s Handloads{% endblock %}

{%block content %}
<ul class="gun_listing">
{% for gun in guns %}
    <li><a href="/gun/{{ gun.id }}/">{{ gun }}</a></li>
{% endfor %}
</ul>

{% if is_paginated %}
<div class="pagination">
    <a href="/reports/?page=1">&lt;&lt;</a> |
    {% if page_obj.has_previous %}
    <a href="/reports/?page={{ page_obj.previous_page_number }}">&lt;</a> |
    {% endif %}
    {{ page_obj }}
    {% if page_obj.has_next %}
    | <a href="/reports/?page={{ page_obj.next_page_number }}">&gt;</a>
    | <a href="/reports/?page=last">&gt;&gt;</a>
    {% endif %}
</div>
{% endif %}
{% endblock %}

templates/rangereport/handload_form.html
{% extends "base.html" %}

{% block content %}
<div class="form">
    <form method="post" action="">
    	{{ form.as_p }}
	<p><input type="submit" value="Submit" /> <input type="reset" value="Reset Form" />
    </form>
</div>
{% endblock %}

templates/rangereport/handload_list.html
{% extends "base.html" %}

{% block title %}Handloads{% endblock %}

{% block header %}<a class="userlink" href="/user/{{ slug }}/"><img src="usericon.gif" alt="Rangedogs User" />{{ slug }}</a>'s Handloads{% endblock %}

{% block content %}
<ul class="handload_listing">
{% for handload in handloads_list %}
    <li>{{ handload }}</li>
{% endfor %}
</ul>
{% endblock %}

templates/rangereport/report_form.html
{% extends "base.html" %}

{% block title %}New Report{% endblock %}

{% block header %}Create a new range report{% endblock %}

{% block content %}
<div class="form">
    <form method="post" action="">
    	{{ form.as_p }}
	<p><input type="submit" value="Submit" /> <input type="reset" value="Reset Form" />
    </form>
</div>
{% endblock %}

templates/rangereport/report_list.html
{% extends "base.html" %}
{% load rr_extras %}

{% block title %}Range Reports{% endblock %}

{% block header %}{% ifequal add_title "user" %}<a class="userlink" href="/user/{{ slug }}/"><img src="usericon.gif" alt="Rangedogs User" />{{ slug }}</a>'s{% else %}Recent{% endifequal %} Range Reports{% endblock %}

{% block content %}
{% for report in reports_list %}
<div class="report_listing">
    <span class="report_listing_title">{{ report.title }}</span> posted by <a class="userlink" href="/user/{{ report.owner.username }}/">{{ report.owner.username }}</a> on {{ report.ctime|date:"D d M Y" }}
    <span class="report_listing_snippet">{{ report.body|truncatewords:100|striptags }}</span>
    <span class="report_listing_participants">{{ report.participants|linkusers }}</span>
    <span class="report_listing_guns">
        {% for gun in report.guns %}
        <a href="/gun/{{ gun.gun.id }}/">{{ gun.gun.owner.username }}'s {{ gun.gun.make }} {{ gun.gun.model }} in {{ gun.gun.caliber.name }}</a> 
        {% endfor %}
    </span>
</div>
{% endfor %}

{% if is_paginated %}
<div class="pagination">
    <a href="/reports/?page=1">&lt;&lt;</a> |
    {% if page_obj.has_previous %}
    <a href="/reports/?page={{ page_obj.previous_page_number }}">&lt;</a> |
    {% endif %}
    {{ page_obj }}
    {% if page_obj.has_next %}
    | <a href="/reports/?page={{ page_obj.next_page_number }}">&gt;</a>
    | <a href="/reports/?page=last">&gt;&gt;</a>
    {% endif %}
</div>
{% endif %}
{% endblock %}